---
all:
  children:
    source:
      children:
        source_controller:
          hosts:
            source-controller.example.com:
        source_hub:
          hosts:
            source-hub.example.com:
        source_gateway:
          hosts:
            source-gateway.example.com:
        # source_db group is empty because source uses external RDS
        source_db:
          hosts:
    target:
      children:
        target_controller:
          hosts:
            target-controller.example.com:
        target_hub:
          hosts:
            target-hub.example.com:
        target_gateway:
          hosts:
            target-gateway.example.com:
        # target_db group is empty because target uses external RDS
        target_db:
          hosts:
        target_eda:
          hosts:
            target-eda.example.com:
