---
all:
  children:
    source:
      children:
        source_controller:
          hosts:
            source-controller.example.com:
        source_hub:
          hosts:
            source-hub.example.com:
        source_gateway:
          hosts:
            source-gateway.example.com:
        source_db:
          hosts:
            source-db.example.com:
    target:
      children:
        target_ocp_bastion:
          hosts:
            bastion.example.com:
