---
- name: Delete temporary PostgreSQL deployment
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ ocp_namespace }}"
    name: "{{ temp_postgres_deployment }}"
    state: absent
    wait: true
    wait_timeout: 120

- name: Delete temporary PVC
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    api_version: v1
    kind: PersistentVolumeClaim
    namespace: "{{ ocp_namespace }}"
    name: "{{ temp_pvc_name }}"
    state: absent
    wait: true
    wait_timeout: 120
