---
# Target OpenShift environment settings
ansible_become: false

# OpenShift / Kubernetes settings
kubeconfig: ~/.kube/config
ocp_namespace: aap
aap_instance_name: aap

# Target database connection (for external DB only)
# target_pg_host: target-rds-instance.us-east-1.rds.amazonaws.com
# target_pg_admin_user: postgres

# PostgreSQL StatefulSet name
postgres_statefulset: aap-postgres-15

# Temp PVC settings
temp_pvc_size: 200Gi
temp_pvc_access_mode: ReadWriteOnce

# OCP secret names
controller_secret_name: aap-controller-secret-key
gateway_secret_name: aap-db-fields-encryption-secret
hub_secret_name: aap-hub-db-fields-encryption

# OCP database config secrets
controller_pg_config_secret: aap-controller-postgres-configuration
hub_pg_config_secret: aap-hub-postgres-configuration
gateway_pg_config_secret: aap-gateway-postgres-configuration

# Operator deployments
gateway_operator_deployment: aap-gateway-operator-controller-manager
controller_operator_deployment: automation-controller-operator-controller-manager

# Gateway admin credentials
# gateway_admin_user: admin
# gateway_admin_password: defined in vault.yml
